Implement reusing of async jobs for equivalent requests.
aehrc/pathling pull request #1414
Opened 2023-04-06 02:11 UTC by piotrszul

Resolves #1313.

2023-05-03 10:14 UTC, johngrimes requested changes
Thanks @piotrszul, I've added a few comments / questions.

Once these have been looked at, I think the best way to prove this out is to merge to a release branch and deploy the pre-release image with a conventional cache setup. We will need to do this for both unauthenticated and authenticated configurations.

I have created a couple of related issues that will need to be resolved before this change can be deployed:

- aehrc/pathling-helm#2
- aehrc/pathling-deployment#6

2023-06-21 01:06 UTC, piotrszul commented on fhir-server/src/main/java/au/csiro/pathling/async/RequestTagFactory.java
> +    final Set<String> exludedVaryHeades = new HashSet<>(configuration.getAsync().getExcludeVary());
Done

2023-06-21 03:09 UTC, piotrszul commented on fhir-server/src/main/java/au/csiro/pathling/async/RequestTagFactory.java
> +  RequestTagFactory(@Nonnull Cacheable state, @Nonnull Set<String> salientHeaderNames) {
Done

2023-06-21 03:12 UTC, piotrszul commented on fhir-server/src/main/java/au/csiro/pathling/async/AsyncAspect.java
> +          return (IBaseResource) joinPoint.proceed();
No, because we do call the function with the original arguments (which is the default).
But  did removed the unused args argument to this function.

2023-06-21 23:48 UTC, piotrszul commented on fhir-server/src/main/resources/application.yml
> +      - Accept-Encoding
I have renamed this option to `varyHeadersExcludedFromCacheKey` and also removed the principal all together from the cache key, as for the JWT the principal java object includes the entire token anyway, so it has the same effect as  including the Authorization header in the key.
So now the way to have a shared cache for an authenticated server is to include 'Authorization' in the `varyHeadersExcludedFromCacheKey`

2023-12-01 06:30 UTC, johngrimes commented
I've moved the Helm chart into the main repository, and I've decided to defer the update of the configuration management for now.

I've merged this into the 6.4.0 release.

2023-12-01 07:46 UTC, merged