Implemented URN reference rewriting for Bundles.
aehrc/pathling pull request #1436
Opened 2023-05-04 06:08 UTC by piotrszul

Resolves: #1434

2023-05-09 21:10 UTC, johngrimes requested changes
Looks great @piotrszul!

Just a few minor things I noticed.

2023-05-09 21:11 UTC, johngrimes commented
Would you mind also taking a look at CVE-2023-20862, so that we can get the Docker image test green?

2023-05-09 21:12 UTC, johngrimes commented
I've tested this out with some Bundle-based analysis, all seems to work perfectly now! 🏅

2023-05-09 23:36 UTC, piotrszul commented on encoders/src/main/java/au/csiro/pathling/support/r4/R4FhirConversionSupport.java
> +  private static void resolveURNReferences(Resource resource) {
Fixed.

2023-05-09 23:38 UTC, piotrszul commented on library-api/src/test/java/au/csiro/pathling/examples/EncodeBundles.java
> +    //
This was some testing code that I have checked in by mistake.
Deleted.

2023-05-09 23:39 UTC, piotrszul commented on library-api/src/test/java/au/csiro/pathling/examples/EncodeBundles.java
> +public class EncodeBundles {
This was some testing code that I have checked in by mistake.
Deleted.

2023-05-09 23:43 UTC, piotrszul commented on encoders/src/test/java/au/csiro/pathling/support/r4/R4FhirConversionSupportTest.java
> +    IBaseResource referenceResource = new Patient().setId(new IdType("Patient", "1234"));
Done.

2023-05-10 05:14 UTC, johngrimes approved these changes
Thanks, looks good.

2023-05-10 05:14 UTC, merged