Add support for FHIR extensions.
aehrc/pathling pull request #429
Opened 2022-02-01 01:38 UTC by piotrszul

Resolves #163

2022-02-21 02:00 UTC, johngrimes requested changes
Looks great, thanks for your work!

I've added a few questions and suggestions for you to take a look at.

2022-02-23 04:29 UTC, piotrszul commented on encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala
> +    val skipModifierExtension = child.getElementName.equals("modifierExtension")
Reported as: https://github.com/hapifhir/hapi-fhir/issues/3414
Updated the comment as well.

2022-02-23 04:41 UTC, piotrszul commented on encoders/src/main/scala/au/csiro/pathling/encoders2/SerializerBuilder2.scala
> +        // TODO: fix the type cast
None

2022-02-23 04:43 UTC, piotrszul commented on encoders/src/test/java/au/csiro/pathling/encoders/ResourceEncodingTest.java
> +      new R4DataTypeMappings(), EncoderConfig.apply(0, true));
It should be SchemaConverter2.
It's designed to test the current default version (v2).

2022-02-23 04:49 UTC, piotrszul commented on fhir-server/src/main/scala/au/csiro/pathling/sql/PathlingExpressions.scala
> +case class Normalize(child: Expression) extends UnaryExpression with CodegenFallback with NullIntolerant {
Changed to `PruneSyntheticFields`

2022-02-23 05:25 UTC, piotrszul commented on encoders/src/test/java/au/csiro/pathling/encoders/TestData.java
> +    //        - value: 11
No, at the moment extending of primitive elements is not implemented (and thus we would not be able use this specific extension type as it extends primitives dateTime/time).
I was thinking to address these more exotic cases as a seperate issue once we understand the impact of the current implementation for composite types on performance and validate in in general.

2022-02-23 05:29 UTC, piotrszul commented on encoders/src/main/scala/au/csiro/pathling/encoders2/SchemaTraversal.scala
> +    // Not if it will be needed anymore if I can do recursive contexts
None.

2022-02-23 05:42 UTC, piotrszul commented on encoders/src/main/scala/au/csiro/pathling/encoders2/DeserializerBuilder2.scala
> +          // Which may actually be OK, but s
Updated the comment.

2022-02-23 06:01 UTC, piotrszul commented on encoders/src/main/scala/au/csiro/pathling/encoders/EncoderContext.scala
> +                         override val generateFid: Boolean) extends EncoderSettings {
Maybe but I am not sure about it. 
This config is more 'internal' and at least until we get rid of V1 encoders have options that should be available for FhirEncoders.
Perhaps we could revisit it when we remove V1 encoders.

2022-02-23 06:10 UTC, piotrszul commented on encoders/src/main/java/au/csiro/pathling/encoders/FhirEncoders.java
>    public static class Builder {
Updated.

2022-02-24 00:28 UTC, johngrimes commented on fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
> +  }
This has now been fixed on `release/5.0.0`, and I have merged it in and confirmed that it is working.

2022-02-24 00:32 UTC, johngrimes commented on encoders/src/test/java/au/csiro/pathling/encoders/TestData.java
> +    //        - value: 11
I have created a new issue for this: #437

2022-02-24 00:34 UTC, johngrimes commented on encoders/src/main/scala/au/csiro/pathling/encoders/EncoderContext.scala
> +                         override val generateFid: Boolean) extends EncoderSettings {
I have added an issue relating to the removal of the v1 encoders: #438

2022-03-07 05:40 UTC, johngrimes approved these changes

2022-03-07 05:40 UTC, merged