Python API for encoders.
aehrc/pathling pull request #494
Opened 2022-04-19 03:45 UTC by piotrszul

Resolves #452

2022-04-26 07:48 UTC, kapsner commented
Hi @piotrszul,

thanks for providing this pull request. I have just tried to install the python dev-version, but unfortunatelly the file `_version.py` (referenced [here](https://github.com/aehrc/pathling/blob/issue/452/lib/python/setup.py#L9)) seems to be missing in the repo, leading to the following error message:

```
#0 7.406 Obtaining file:///home/jovyan/pathling/lib/python
#0 7.407   Preparing metadata (setup.py): started
#0 7.739   Preparing metadata (setup.py): finished with status 'error'
#0 7.748   error: subprocess-exited-with-error
#0 7.748
#0 7.748   × python setup.py egg_info did not run successfully.
#0 7.748   │ exit code: 1
#0 7.748   ╰─> [6 lines of output]
#0 7.748       Traceback (most recent call last):
#0 7.748         File "<string>", line 2, in <module>
#0 7.748         File "<pip-setuptools-caller>", line 34, in <module>
#0 7.748         File "/home/jovyan/pathling/lib/python/setup.py", line 15, in <module>
#0 7.748           with open(VERSION_FILE) as vf:
#0 7.748       FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/pathling/lib/python/pathling/_version.py'
#0 7.748       [end of output]
#0 7.748
#0 7.748   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 7.752 error: metadata-generation-failed
#0 7.752
#0 7.752 × Encountered error while generating package metadata.
#0 7.752 ╰─> See above for output.
#0 7.752
#0 7.752 note: This is an issue with the package mentioned above, not pip.
#0 7.752 hint: See above for details.
```

2022-04-27 07:52 UTC, kapsner commented
Hi again, first of all thank you very very much on your efforts and activities to implement this python API!

I have just tried to re-run the installation with the updated instructions and run into the following messages:

```bash
cd pathling/lib/python && \
    mvn -f ../../encoders/ -DskipTests=true clean install
```

gives:

>.....
Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar (202 kB at 1.5 MB/s)
Progress (4): 153 kB | 360/472 kB | 155/167 kB | 36/209 kB
#0 31.08 [output clipped, log limit 1MiB reached]
#0 58.09 warning: one deprecation
#0 58.10 warning: three deprecations (since 2.12.0)
#0 58.10 warning: one deprecation (since 2.12.13)
#0 58.10 warning: two deprecations (since 2.12.9)
#0 58.10 warning: 7 deprecations in total; re-run with -deprecation for details
#0 58.10 warning: three feature warnings; re-run with -feature for details

Then I tried with the flag "-fn":

```bash
cd pathling/lib/python && \
    mvn -f ../../encoders/ -DskipTests=true -fn clean install && \
    mvn clean compile
```

Which results in:

>#0 1.451 WARNING: An illegal reflective access operation has occurred
#0 1.451 WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 
(file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
#0 1.451 WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
#0 1.451 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
#0 1.451 WARNING: All illegal access operations will be denied in a future release
#0 2.017 [INFO] Scanning for projects...
#0 2.355 [INFO]
#0 2.358 [INFO] ----------------------< au.csiro.pathling:python >----------------------
#0 2.362 [INFO] Building Pathling Python 5.0.0
#0 2.371 [INFO] --------------------------------[ jar ]---------------------------------
#0 2.693 Downloading from central: https://repo.maven.apache.org/maven2/ru/yaal/maven/write-text-files-maven-plugin/1.1/write-text-files-maven-plugin-1.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/ru/yaal/maven/write-text-files-maven-plugin/1.1/write-text-files-maven-plugin-1.1.pom (6.2 kB at 18 kB/s)
#0 3.044 Downloading from central: https://repo.maven.apache.org/maven2/ru/yaal/maven/write-text-files-maven-plugin/1.1/write-text-files-maven-plugin-1.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/ru/yaal/maven/write-text-files-maven-plugin/1.1/write-text-files-maven-plugin-1.1.jar (7.0 kB at 207 kB/s)
#0 3.086 Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.2.0/maven-dependency-plugin-3.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.2.0/maven-dependency-plugin-3.2.0.pom (18 kB at 421 kB/s)
#0 3.142 Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.2.0/maven-dependency-plugin-3.2.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.2.0/maven-dependency-plugin-3.2.0.jar (205 kB at 2.4 MB/s)
#0 3.263 Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/3.0.0/exec-maven-plugin-3.0.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/3.0.0/exec-maven-plugin-3.0.0.pom (14 kB at 503 kB/s)
#0 3.296 Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/50/mojo-parent-50.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/50/mojo-parent-50.pom (34 kB at 1.0 MB/s)
#0 3.340 Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/3.0.0/exec-maven-plugin-3.0.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/3.0.0/exec-maven-plugin-3.0.0.jar (68 kB at 1.9 MB/s)
#0 3.414 Downloading from central: https://repo.maven.apache.org/maven2/au/csiro/pathling/encoders/5.0.0/encoders-5.0.0.pom
#0 3.593 [WARNING] The POM for au.csiro.pathling:encoders:jar:5.0.0 is missing, no dependency information available
#0 3.602 Downloading from central: https://repo.maven.apache.org/maven2/au/csiro/pathling/encoders/5.0.0/encoders-5.0.0.jar
#0 3.767 [INFO] ------------------------------------------------------------------------
#0 3.768 [INFO] BUILD FAILURE
#0 3.769 [INFO] ------------------------------------------------------------------------
#0 3.771 [INFO] Total time:  1.779 s
#0 3.771 [INFO] Finished at: 2022-04-27T07:45:40Z
#0 3.772 [INFO] ------------------------------------------------------------------------
#0 3.773 [ERROR] Failed to execute goal on project python: Could not resolve dependencies for project au.csiro.pathling:python:jar:5.0.0: Could not find artifact au.csiro.pathling:encoders:jar:5.0.0 in 
central (https://repo.maven.apache.org/maven2) -> [Help 1]
#0 3.779 [ERROR]
#0 3.780 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 3.781 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 3.781 [ERROR]
#0 3.781 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 3.782 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

2022-05-01 06:35 UTC, johngrimes commented
Hi @kapsner,

I've made some changes to the build that make it a bit easier.

Try this from the root of the repository:

```bash
mvn clean install -pl lib/python -am
```

This should run all the required steps, including installing all dependencies, building the package, and installing the package.

After this, you should be able to:

```bash
pip install pathling
```

Let us know if you have any problems.

2022-05-01 06:38 UTC, johngrimes commented
We haven't uploaded the package to PyPI yet, but if you give it a bit of a test for us we will organise that ASAP.

2022-05-10 10:19 UTC, kapsner commented
Short intermediate feedback: the `find_jars()` method is very very convenient and works perfectly so far. We are still evaluating the python API and are now trying migrate from the toy-datasets to apply it to some "real" FHIR resources to get a better understanding of the solving of real-world-problems.

However, so far we did not encounter any issues yet.

2022-05-11 01:26 UTC, johngrimes commented
Hi @kapsner and @jasminziegler, (cc @piotrszul)

I think I got it working, with some modifications to your Dockerfile and Python script (or at least got past the error that you encountered).

I built the new Pathling python library, and put the wheel into the Docker image and installed it:

```Dockerfile
FROM jupyter/minimal-notebook:latest

USER root

COPY pathling-5.0.2-py2.py3-none-any.whl /home/jovyan/pathling-5.0.2-py2.py3-none-any.whl

# install java
RUN apt-get update && apt-get install -y --no-install-recommends \
    default-jre

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
ENV PATH=$PATH:$JAVA_HOME/bin

# must match with spark-version from spark-container
ENV SPARK_VERSION=3.2.1
# must match witch major-minor version of scala
# (find out in spark container running command 'spark-shell')
ENV SPARK_SCALA_VERSION=2.12

# define submit-args (this is working now 15.3.2022 lorenz)
ENV PYSPARK_SUBMIT_ARGS=" \
    --packages org.apache.spark:spark-sql-kafka-0-10_$SPARK_SCALA_VERSION:$SPARK_VERSION \
    pyspark-shell"

# python-version from spark must match version form jupyter / client (python 3.8)
# create conda env with python 3.8
RUN conda install python=3.8 
RUN pip install pyspark==${SPARK_VERSION} pandas
RUN pip install pathling-5.0.2-py2.py3-none-any.whl
```

Then I modified your Python script to use the Pathling library, instead of Bunsen:

```python
#!/bin/python

appName = "Kafka, Spark and FHIR Data"
master = "spark://spark:7077"
kafka_topic = "fhir.post-gateway-kdb"

from pathling.r4.bundles import from_json, extract_entry
from pathling.etc import find_jar
from pyspark.sql import SparkSession

if __name__ == "__main__":

    spark = SparkSession \
        .builder \
        .appName(appName) \
        .master(master) \
        .config('spark.jars', find_jar()) \
        .getOrCreate()

    df = spark \
        .readStream  \
        .format("kafka") \
        .option("kafka.bootstrap.servers", "kafka1:19092") \
        .option("subscribe", kafka_topic) \
        .option("startingOffsets", "earliest") \
        .load()

    df.printSchema()

    query = df.selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)") \
            .writeStream \
            .queryName("gettable")\
            .format("memory")\
            .start()

    # close connection after 15 seconds
    query.awaitTermination(15)

    mydf = spark.sql("select * from gettable")
    mydf.show()
    type(mydf)

    df = mydf.toPandas()
    df

    mydf_rdd = mydf.rdd
    type(mydf_rdd) # convert to javaRDD for bunsen?

    # the bunsen r4 part is failing (probably due to using old pyspark=2.4.4)
    bundles = from_json(mydf_rdd, 'value')
    conditions = extract_entry(spark, from_json(mydf, 'value'), 'Condition')
```

Is this the same process you followed? If not, would you mind providing your updated code so that we can reproduce the problem more closely?

When I first saw the error that you were getting, I thought it must be related to the availability of the `org.apache.spark:spark-sql-kafka-0-10_$SPARK_SCALA_VERSION:$SPARK_VERSION` JAR on the classpath. However, that package seems to load fine when I run the (modified) image:

```
:: loading settings :: url = jar:file:/opt/conda/lib/python3.8/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-93cdf69f-a40f-4c5f-bd12-a5676079d71f;1.0
        confs: [default]
        found org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1 in central
        found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.1 in central
        found org.apache.kafka#kafka-clients;2.8.0 in central
        found org.lz4#lz4-java;1.7.1 in central
        found org.xerial.snappy#snappy-java;1.1.8.4 in central
        found org.slf4j#slf4j-api;1.7.30 in central
        found org.apache.hadoop#hadoop-client-runtime;3.3.1 in central
        found org.spark-project.spark#unused;1.0.0 in central
        found org.apache.hadoop#hadoop-client-api;3.3.1 in central
        found org.apache.htrace#htrace-core4;4.1.0-incubating in central
        found commons-logging#commons-logging;1.1.3 in central
        found com.google.code.findbugs#jsr305;3.0.0 in central
        found org.apache.commons#commons-pool2;2.6.2 in central
downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.1/spark-sql-kafka-0-10_2.12-3.2.1.jar ...
        [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1!spark-sql-kafka-0-10_2.12.jar (414ms)
downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.2.1/spark-token-provider-kafka-0-10_2.12-3.2.1.jar ...
        [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.1!spark-token-provider-kafka-0-10_2.12.jar (177ms)
downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.0/kafka-clients-2.8.0.jar ...
        [SUCCESSFUL ] org.apache.kafka#kafka-clients;2.8.0!kafka-clients.jar (756ms)
downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
        [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (170ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.6.2/commons-pool2-2.6.2.jar ...
        [SUCCESSFUL ] org.apache.commons#commons-pool2;2.6.2!commons-pool2.jar (172ms)
downloading https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar ...
        [SUCCESSFUL ] org.spark-project.spark#unused;1.0.0!unused.jar (169ms)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.1/hadoop-client-runtime-3.3.1.jar ...
        [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.1!hadoop-client-runtime.jar (1598ms)
downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.jar ...
        [SUCCESSFUL ] org.lz4#lz4-java;1.7.1!lz4-java.jar (178ms)
downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar ...
        [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.8.4!snappy-java.jar(bundle) (196ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar ...
        [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.30!slf4j-api.jar (171ms)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.1/hadoop-client-api-3.3.1.jar ...
        [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.1!hadoop-client-api.jar (917ms)
downloading https://repo1.maven.org/maven2/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar ...
        [SUCCESSFUL ] org.apache.htrace#htrace-core4;4.1.0-incubating!htrace-core4.jar (193ms)
downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
        [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (171ms)
:: resolution report :: resolve 28845ms :: artifacts dl 5292ms
        :: modules in use:
        com.google.code.findbugs#jsr305;3.0.0 from central in [default]
        commons-logging#commons-logging;1.1.3 from central in [default]
        org.apache.commons#commons-pool2;2.6.2 from central in [default]
        org.apache.hadoop#hadoop-client-api;3.3.1 from central in [default]
        org.apache.hadoop#hadoop-client-runtime;3.3.1 from central in [default]
        org.apache.htrace#htrace-core4;4.1.0-incubating from central in [default]
        org.apache.kafka#kafka-clients;2.8.0 from central in [default]
        org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1 from central in [default]
        org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.1 from central in [default]
        org.lz4#lz4-java;1.7.1 from central in [default]
        org.slf4j#slf [...]

2022-05-11 05:42 UTC, kapsner commented
Hi @johngrimes , many thanks for your help and answer.

>If not, would you mind providing your updated code so that we can reproduce the problem more closely?

Ah, sorry - I have done all pathling-adaptions in a fork of the [demo-kafka-spark-pipeline](https://github.com/kapsner/demo-kafka-spark-pipeline/tree/add_pathling), but installing pathling directly from git instead of first building the wheel and copying it into the image (https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_pathling/Dockerfile).
 
The updated script using pathling instead of Bunsen is located here: [https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_pathling/volume/kafka_stream_con.py](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_pathling/volume/kafka_stream_con.py)

The JAR `org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1` indeed has always been loaded fine ([code here](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_pathling/volume/kafka_stream_con.py#L24)).

The issue occurs when running [this code](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_pathling/volume/kafka_stream_con.py#L34).

2022-05-11 06:26 UTC, johngrimes commented
This is the output I got from running `start.sh`:

```
➜ bash start.sh 
[+] Building 697.9s (12/12) FINISHED                                                                                                                                                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                  0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/jupyter/minimal-notebook:latest                                                                                                                                                                                                            0.0s
 => [1/8] FROM docker.io/jupyter/minimal-notebook:latest                                                                                                                                                                                                                              0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install -y --no-install-recommends     default-jdk     make                                                                                                                                                                            0.0s
 => CACHED [3/8] RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz -P /tmp &&     tar xf /tmp/apache-maven-*.tar.gz -C /opt &&     ln -s /opt/apache-maven-3.8.5 /opt/maven                                                                0.0s
 => [4/8] RUN mvn -version                                                                                                                                                                                                                                                            0.3s
 => [5/8] RUN conda install python=3.8                                                                                                                                                                                                                                               67.4s
 => [6/8] RUN pip install pyspark==3.2.1 pandas                                                                                                                                                                                                                                      25.0s 
 => [7/8] RUN git clone -b issue/452 https://github.com/kapsner/pathling.git                                                                                                                                                                                                          6.4s 
 => [8/8] RUN cd pathling &&     mvn -q clean install -pl lib/python -am                                                                                                                                                                                                            592.1s 
 => exporting to image                                                                                                                                                                                                                                                                6.6s 
 => => exporting layers                                                                                                                                                                                                                                                               6.6s 
 => => writing image sha256:fd31a10f6988112b2626e84e81c8e628842ef13bd4b55a9382a236657df4e169                                                                                                                                                                                          0.0s 
 => => naming to docker.io/library/jupyter-pathling                                                                                                                                                                                                                                   0.0s 
Creating spark            ... done
Creating jupyter-pathling ... done
Creating zoo1             ... done
Creating spark-worker     ... done
Creating kafka1           ... done
Creating akhq             ... done
Creating mock-data-loader ... done
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/conda/lib/python3.8/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
:: loading settings :: url = jar:file:/opt/conda/lib/python3.8/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-5ebbd112-da04-43de-9ce1-ea0637c846d4;1.0
        confs: [default]
        found org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1 in central
        found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.1 in central
        found org.apache.kafka#kafka-clients;2.8.0 in central
        found org.lz4#lz4-java;1.7.1 in local-m2-cache
        found org.xerial.snappy#snappy-java;1.1.8.4 in local-m2-cache
        found org.slf4j#slf4j-api;1.7.30 in local-m2-cache
        found org.apache.hadoop#hadoop-client-runtime;3.3.1 in local-m2-cache
        found org.spark-project.spark#unused;1.0.0 in local-m2-cache
        found org.apache.hadoop#hadoop-client-api;3.3.1 in local-m2-cache
        found org.apache.htrace#htrace-core4;4.1.0-incubating in local-m2-cache
        found commons-logging#commons-logging;1.1.3 in local-m2-cache
        found com.google.code.findbugs#jsr305;3.0.0 in central
        found org.apache.commons#commons-pool2;2.6.2 in central
downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.1/spark-sql-kafka-0-10_2.12-3.2.1.jar ...
        [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.1!spark-sql-kafka-0-10_2.12.jar (949ms)
downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.2.1/spark-token-provider-kafka-0-10_2.12-3.2.1.jar ...
        [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.1!spark-token-provider-kafka-0-10_2.12.jar (234ms)
downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.0/kafka-clients-2.8.0.jar ...
        [SUCCESSFUL ] org.apache.kafka#kafka-clients;2.8.0 [...]

2022-05-11 10:59 UTC, kapsner commented
Hi @johngrimes , thanks again for your quick answer. I am working on a Windows 10 host using Docker Desktop 4.7.0 (77141).

That is really strange, it indeed seems as if there were no data available in kafka in your run of the script. Sometimes, the mock-data-loader somehow fails to populate the data in kafka. To check if data is available in kafka, you can open [http://localhost:8082/ui/docker-kafka-server/topic](http://localhost:8082/ui/docker-kafka-server/topic) once the setup has started. There should be one topic available with 5 ressources:
![grafik](https://user-images.githubusercontent.com/44973495/167833715-6129d27f-9470-47da-ba77-b71ce388dfb4.png)

I have just purged all docker images and re-ran the `./start.sh` from [https://github.com/kapsner/demo-kafka-spark-pipeline/tree/add_pathling](https://github.com/kapsner/demo-kafka-spark-pipeline/tree/add_pathling), which gives the following output:

```
$ ./start.sh
[+] Building 951.7s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                     0.0s 
 => => transferring dockerfile: 32B                                                                                                                                                                                                                      0.0s 
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s 
 => => transferring context: 2B                                                                                                                                                                                                                          0.0s 
 => [internal] load metadata for docker.io/jupyter/minimal-notebook:latest                                                                                                                                                                               0.8s 
 => CACHED [1/8] FROM docker.io/jupyter/minimal-notebook:latest@sha256:a1d7b461561f795654e960ded1e7def2f7f62cefac0ac82abef2dc568e2f7d1e                                                                                                                  0.0s 
 => [2/8] RUN apt-get update && apt-get install -y --no-install-recommends     default-jdk     make                                                                                                                                                    148.4s 
 => [3/8] RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz -P /tmp &&     tar xf /tmp/apache-maven-*.tar.gz -C /opt &&     ln -s /opt/apache-maven-3.8.5 /opt/maven                                          1.4s 
 => [4/8] RUN mvn -version                                                                                                                                                                                                                               0.7s 
 => [5/8] RUN conda install python=3.8                                                                                                                                                                                                                 232.4s 
 => [6/8] RUN pip install pyspark==3.2.1 pandas                                                                                                                                                                                                         62.1s 
 => [7/8] RUN git clone -b issue/452 https://github.com/kapsner/pathling.git                                                                                                                                                                             8.2s 
 => [8/8] RUN cd pathling &&     mvn -q clean install -pl lib/python -am                                                                                                                                                                               489.2s 
 => exporting to image                                                                                                                                                                                                                                   8.4s 
 => => exporting layers                                                                                                                                                                                                                                  8.3s 
 => => writing image sha256:69bd99086c96e4f2ea253ed9bfd5c6611e0d35fa2b3cd9dfc91e8124c63d892f                                                                                                                                                             0.0s 
 => => naming to docker.io/library/jupyter-pathling                                                                                                                                                                                                      0.0s 
[+] Running 47/47
 - zoo1 Pulled                                                                                                                                                                                                                                         125.9s 
   - 1fe172e4850f Pull complete                                                                                                                                                                                                                        101.9s 
   - 44d3aa8d0766 Pull complete                                                                                                                                                                                                                        102.2s 
   - fda2f211fa11 Pull complete                                                                                                                                                                                                                        102.3s 
   - 9154e8aefca7 Pull complete                                                                                                                                                                                                                        122.1s 
   - 692fa00e9b62 Pull complete                                                                                                                                                                                                                        122.3s 
   - a17c9a9b7c3c Pull complete                                                                                                                                                                                                                        122.8s
   - 58c5fef3f1f5 Pull complete                                                                                                                                                                                                                        123.9s 
   - 58060ca669c1 Pull complete                                                                                                                                                                                                                        124.0s 
 - spark Pulled                                                                                                                                                                                                                                        217.7s 
   - c9aaae6acc00 Pull complete                                                                                                [...]

2022-05-11 13:16 UTC, kapsner commented
FYI: I was just able to reproduce the error on a Ubuntu 20.04 workstation.

2022-05-12 07:35 UTC, johngrimes commented
Hi @kapsner and @jasmineziegler,

We've worked out what the problem was. It was related to overwriting the JAR path rather than adding to it within the Python script.

We've fixed this by publishing the encoders JAR to Maven (currently just as a snapshot), and adding it to the list of packages in `PYSPARK_SUBMIT_ARGS`.

https://pypi.org/project/pathling/

`au.csiro.pathling:encoders:5.0.3-SNAPSHOT`

I've created a pull request that hopefully communicates these changes: https://github.com/kapsner/demo-kafka-spark-pipeline/pull/1

Unfortunately the Bitnami images you are using for Spark are based on Java 8 are not compatible with Pathling, which requires Java 11.

2022-05-12 08:29 UTC, jasminziegler commented
@johngrimes this is great news - many thanks for your support!

2022-05-12 08:31 UTC, kapsner commented
Hi @johngrimes ,

Wow, many many thanks for your efforts and help - the updated setup works perfectly now. We have just decided to stay with the local spark for our further tests with real-world FHIR resources and plan to switch to a spark cluster at a later stage, once everything else is working!

2022-05-12 11:54 UTC, kapsner commented
Haha :) I just tried to reproduce the issue from before and I was initially successful reproducing it from the jupyter-notebook, however, when trying to put everything into the python-script triggered from `start.sh`, the issue disappeared...

What I did (on branch [add_spark_cluster](https://github.com/kapsner/demo-kafka-spark-pipeline/tree/add_spark_cluster)):
- set up a spark-cluster (according to https://www.kdnuggets.com/2020/07/apache-spark-cluster-docker.html) based on java-11 and integrate it again into the framework (similar as before when using the bitnami-setup)
- I then ran `start.sh` followed by `docker logs -f jupyter-pathling` to open [the notebook](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_spark_cluster/volume/getting_started_with_pathling.ipynb) from the jupyterlab
- there, I could reproduce the error simply by changing the spark master from `"local[*]"` to `"spark://spark-master:7077"` (which demonstrated that the issue seems also to be present on a java-11 spark base image)
- I then wanted to update the [python script](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_spark_cluster/volume/kafka_stream_con.py) to demonstrate that the issue shows up when running on the remote spark-cluster compared to the local one
- however, strangely, the issue somehow did not show up and instead the script ran successfully also on the remote spark cluster (yeah!!!)

However, the different behavior when executing the script directly in the container opposed to when running the jupyter-notebook is really strange since both JupyterLab and the python script are executed in the very same docker-container.

I was not yet able to find the exact cause, but I somehow think that there is some misconfiguration of spark when creating the session from the jupyter-notebook...

Any ideas on that?

2022-05-12 21:00 UTC, kapsner commented
I was finally able to figure it out:

The major difference I've found when comparing the spark-configs between the python-script and the jupyterlab were the following:

Using `spark.sparkContext.getConf().getAll()`, the `spark.jars` from the jupyterlab spark-session are:

> ('spark.jars', '/opt/conda/lib/python3.9/site-packages/pathling/jars/encoders-5.0.3-SNAPSHOT-all.jar'), 

whereas those from the session that is built from the python script are:

>('spark.jars', 'file:///home/jovyan/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.2.1.jar,file:///home/jovyan/.ivy2/jars/au.csiro.pathling_encoders-5.0.3-SNAPSHOT.jar,file:///home/jovyan/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.2.1.jar,file:///home/jovyan/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.0.jar,file:///home/jovyan/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar,file:///home/jovyan/.ivy2/jars/org.apache.commons_commons-pool2-2.6.2.jar,file:///home/jovyan/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar,file:///home/jovyan/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.1.jar,file:///home/jovyan/.ivy2/jars/org.lz4_lz4-java-1.7.1.jar,file:///home/jovyan/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar,file:///home/jovyan/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.1.jar,file:///home/jovyan/.ivy2/jars/org.apache.htrace_htrace-core4-4.1.0-incubating.jar,file:///home/jovyan/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar,file:///home/jovyan/.ivy2/jars/ca.uhn.hapi.fhir_hapi-fhir-base-5.7.2.jar,file:///home/jovyan/.ivy2/jars/ca.uhn.hapi.fhir_hapi-fhir-structures-r4-5.7.2.jar,file:///home/jovyan/.ivy2/jars/com.fasterxml.jackson.datatype_jackson-datatype-jsr310-2.13.2.jar,file:///home/jovyan/.ivy2/jars/com.fasterxml.jackson.core_jackson-databind-2.13.2.1.jar,file:///home/jovyan/.ivy2/jars/org.apache.commons_commons-lang3-3.12.0.jar,file:///home/jovyan/.ivy2/jars/org.apache.commons_commons-text-1.9.jar,file:///home/jovyan/.ivy2/jars/commons-codec_commons-codec-1.15.jar,file:///home/jovyan/.ivy2/jars/commons-io_commons-io-2.11.0.jar,file:///home/jovyan/.ivy2/jars/com.google.guava_guava-31.0.1-jre.jar,file:///home/jovyan/.ivy2/jars/org.slf4j_slf4j-api-1.7.36.jar,file:///home/jovyan/.ivy2/jars/com.fasterxml.jackson.core_jackson-annotations-2.13.2.jar,file:///home/jovyan/.ivy2/jars/com.fasterxml.jackson.core_jackson-core-2.13.2.jar,file:///home/jovyan/.ivy2/jars/com.google.guava_failureaccess-1.0.1.jar,file:///home/jovyan/.ivy2/jars/com.google.guava_listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar,file:///home/jovyan/.ivy2/jars/org.checkerframework_checker-qual-3.12.0.jar,file:///home/jovyan/.ivy2/jars/com.google.errorprone_error_prone_annotations-2.7.1.jar,file:///home/jovyan/.ivy2/jars/com.google.j2objc_j2objc-annotations-1.3.jar,file:///home/jovyan/.ivy2/jars/com.squareup.okhttp3_okhttp-3.14.9.jar,file:///home/jovyan/.ivy2/jars/ca.uhn.hapi.fhir_org.hl7.fhir.utilities-5.6.27.jar,file:///home/jovyan/.ivy2/jars/ca.uhn.hapi.fhir_org.hl7.fhir.r4-5.6.27.jar,file:///home/jovyan/.ivy2/jars/com.squareup.okio_okio-1.17.2.jar'),

I then realized, that I have (unintentionally) just forgot to add the `.config('spark.jars', find_jar())`-part for setting up the spark session when updating the [python script](https://github.com/kapsner/demo-kafka-spark-pipeline/blob/add_spark_cluster/volume/kafka_stream_con.py#L26) to work with pathling. This part was, however, added to the [jupyter-notebook](https://github.com/kapsner/demo-kafka-spark-pipeline/commit/f17ce8008c63991a118bc855593df0db9fc9b13a#diff-ad7749bd8b9a5bf63c42097169d75119624f8eb7ba0e9edfc59f6c37c1aba6feL165) for testing purposes.

Removing `.config('spark.jars', find_jar())` when setting up the spark session in the [jupyter-notebook](https://github.com/kapsner/demo-kafka-spark-pipeline/commit/f17ce8008c63991a118bc855593df0db9fc9b13a#diff-ad7749bd8b9a5bf63c42097169d75119624f8eb7ba0e9edfc59f6c37c1aba6feL165) solved the issue - everything is now working fine also when using a "spark cluster" (aka. spark running in different containers).

So, when exactly is it recommended to use the `find_jar()`-method?

I've initially just copy-pasted the example from the [pathling-readme](https://github.com/aehrc/pathling/blob/issue/452/lib/python/README.md#usage) assuming that this part is important for using pathling somehow.

2022-05-17 06:48 UTC, johngrimes commented
I think there are a couple of things left to do on this PR.

First of all, I think we should remove the functional overlap with the Spark reader in terms of loading text files. With Spark, you can already load text files with one line as a row, or alternately with one file as a row. This provides what we need to load both Bundles and NDJSON as strings.

Then we just need two functions:

- encode (takes a dataframe with a single JSON resource in each row)
- encode_from_bundle (takes a dataframe with a JSON Bundle in each row, and also takes an argument which tells it which resource type to extract and encode)

We also need to move away from RDDs within the internal implementation of these functions towards the structured API, so as to preserve the ability to encode within a stream.

I think we should move these functions into a `PathlingContext` object, which we would probably just initialize with a `SparkSession` for now. This removes the need to pass `spark` as an argument to the functions, and it also provides a place to add additional functionality and configuration when we expand the library beyond just the encoders (e.g. terminology functions, Pathling operations such as aggregate, extract, etc.).

So the workflow might look more like this for Bundles:

```python
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
pathling = PathlingContext(spark)
fhir_bundles_dir = os.path.join('bundles/')

bundle_strings = spark.read.text(fhir_bundles_dir, wholetext=True)
patient_dataset = pathling.encode_from_bundles(bundle_strings, 'Patient')
```

And this for NDJSON:

```python
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
pathling = PathlingContext(spark)
patient_ndjson = os.path.join('ndjson/Patient.ndjson')

resource_strings = spark.read.text(patient_ndjson)
patient_dataset = pathling.encode(resource_strings)
```

2022-05-17 06:54 UTC, johngrimes commented
In terms of the JAR, I think we should still bundle it into the package for users that don't have control of the packages that are available to the Spark cluster. So we still need a `find_jar` function.

For users that have the ability to install packages to their cluster or environment, that would still be the preference as it allows for other packages to be included as well (e.g. Kafka). Now that we have published the Maven package for encoders, this makes this a lot easier.

In Databricks, you can search for the Maven package and install it to the cluster via the UI (and also the Python package, as well, so that you don't have to install it from the notebook).

2022-05-18 02:44 UTC, johngrimes commented
Additionally, we might need another argument to `encode` and `encode_from_bundles` to account for different input formats. This would be a valid [FHIR MIME type](https://www.hl7.org/fhir/http.html#mime-type), defaulting to `application/fhir+json`. We can support all three, as they are all supported by HAPI.

To encode from XML Bundles, for example:

```python
patient_dataset = pathling.encode_from_bundles(bundle_strings, 'Patient', 'application/fhir+xml')
```

2022-05-24 06:39 UTC, johngrimes requested changes
The last two things we need to do are:

- [x] Update the README
- [x] Remove the RDF format, as it requires additional dependencies

2022-05-26 05:39 UTC, johngrimes approved these changes

2022-05-30 14:49 UTC, kapsner commented
Thanks for the enhancements - I was able to successfully test them.

One final thing that came to my mind:

- would it make sense to somehow mention the `PYSPARK_SUMIT_ARGS` in the readme to make it easier for future users to get things working?
> APACHE_SPARK_VERSION=3.2.1
SPARK_SCALA_VERSION=2.12
PYSPARK_SUBMIT_ARGS=" \
    --packages org.apache.spark:spark-sql-kafka-0-10_${SPARK_SCALA_VERSION}:$APACHE_SPARK_VERSION,au.csiro.pathling:encoders:5.0.3-SNAPSHOT \
    --repositories https://oss.sonatype.org/content/repositories/snapshots \
    pyspark-shell"

2022-06-06 00:10 UTC, johngrimes commented
Yes, thanks @kapsner - I am working on the documentation at the moment, and will make sure this is covered.

2022-06-06 03:13 UTC, merged